sources:
    - name: staging
      database: data-engineering-398114  # For bigquery project ID
      schema: ny_taxi_data # dataset where the table containing data.

      tables:
        - name: green_tripdata
        - name: yellow_tripdata
          